import { StrictMode, useEffect, useRef, useState, type FormEvent, type PointerEvent } from 'react'
import { createRoot } from 'react-dom/client'
import earthAsset from '../assets/earth.png'
import './styles.css'

const challenges = [
  { number: '01', title: 'Clean air', text: 'Build technology that helps monitor or understand the air we breathe.', icon: '◎', tone: 'mint' },
  { number: '02', title: 'Smarter energy', text: 'Create tools that help people use energy more efficiently.', icon: 'ϟ', tone: 'lime' },
  { number: '03', title: 'Better water', text: 'Build for monitoring, conserving, or improving water resources.', icon: '◒', tone: 'blue' },
  { number: '04', title: 'Less waste', text: 'Create systems that reduce, sort, reuse, or understand waste.', icon: '↻', tone: 'orange' },
  { number: '05', title: 'Connected Earth', text: 'Use sensors, software, AI, or Earth observation to see the bigger picture.', icon: '⌁', tone: 'violet' },
  { number: '06', title: 'Your idea', text: 'Find another meaningful real-world problem. The best ideas may be the ones we have not named yet.', icon: '+', tone: 'yellow' },
]

const buildIdeas = ['Low-cost air-quality sensors', 'Smart irrigation systems', 'Solar tracking systems', 'Energy monitoring devices', 'Automated recycling systems', 'Wildlife monitoring systems', 'Urban heat mapping', 'Earth-observation applications', 'Environmental data platforms']
const impactProjects = [
  { id: '01', location: 'Nairobi, Kenya', problem: 'Water scarcity', technology: 'Solar-powered soil sensors', impact: '18% less water used in pilot farms', latitude: -1.286, longitude: 36.817, x: 68, y: 59 },
  { id: '02', location: 'Reykjavík, Iceland', problem: 'Energy efficiency', technology: 'Open geothermal data platform', impact: '12,400 households mapped', latitude: 64.146, longitude: -21.942, x: 67, y: 42 },
  { id: '03', location: 'São Paulo, Brazil', problem: 'Urban heat', technology: 'Street-level heat mapping', impact: '31 cool corridors identified', latitude: -23.55, longitude: -46.633, x: 38, y: 59 },
  { id: '04', location: 'Bengaluru, India', problem: 'Air quality', technology: 'Low-cost sensor network', impact: 'Real-time data across 8 districts', latitude: 12.972, longitude: 77.594, x: 80, y: 58 },
]
const faqs = [
  ['Who can participate?', 'Young builders ages 13–21. You can participate solo or with a team.'],
  ['Do I need to be an experienced programmer?', 'No. Beginners are welcome, although participants should be prepared to learn and build during the event.'],
  ['Can I use AI?', "Yes, subject to the event's AI-use rules. We care about what you make and how honestly you document your process."],
  ['Can I build hardware?', 'Yes. Hardware, software, sensors, robotics, and hybrid projects are all welcome.'],
  ['Do I have to build something related to climate?', 'No. Projects should address a meaningful real-world challenge connected to Earth, communities, infrastructure, sustainability, science, or related areas.'],
  ['Can I participate remotely?', 'Yes, if the event is being run online. Check the final event format when registration opens.'],
]

function Arrow() { return <span aria-hidden="true">↗</span> }
function Logo() { return <a className="logo" href="#top" aria-label="Build for Earth home"><span className="logo-mark">✳</span><span>BUILD<br /><b>FOR EARTH</b></span></a> }

function Nav({ onRegister }: { onRegister: () => void }) {
  const [open, setOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 24); window.addEventListener('scroll', onScroll, { passive: true }); onScroll(); return () => window.removeEventListener('scroll', onScroll) }, [])
  const links = [['About', 'about'], ['Challenge', 'challenge'], ['Prizes', 'prizes'], ['Timeline', 'timeline'], ['Sponsors', 'sponsors'], ['FAQ', 'faq']]
  return <header className={`nav-wrap ${open ? 'nav-open' : ''} ${scrolled ? 'scrolled' : ''}`}><nav className="nav container"><Logo /><div className="nav-links">{links.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}</div><button className="button button-small nav-cta" onClick={onRegister}>Register <Arrow /></button><button className="menu-button" aria-label="Toggle menu" aria-expanded={open} onClick={() => setOpen(!open)}><i /><i /></button></nav></header>
}

function SectionLabel({ children }: { children: string }) { return <div className="section-label"><span />{children}</div> }

function Earth({ className = '' }: { className?: string }) { return <div className={`earth-visual ${className}`} aria-label="Illustration of planet Earth"><svg viewBox="0 0 500 500" role="img" aria-hidden="true"><defs><radialGradient id="ocean" cx="34%" cy="28%"><stop offset="0" stopColor="#4b9db0" /><stop offset=".48" stopColor="#1d6170" /><stop offset="1" stopColor="#092d38" /></radialGradient><radialGradient id="atmosphere"><stop offset="66%" stopColor="#83cbd0" stopOpacity="0" /><stop offset="84%" stopColor="#83cbd0" stopOpacity=".3" /><stop offset="100%" stopColor="#9fe2dd" stopOpacity="0" /></radialGradient><filter id="cloudBlur"><feGaussianBlur stdDeviation="5" /></filter><clipPath id="earthClip"><circle cx="250" cy="250" r="194" /></clipPath></defs><circle className="earth-atmosphere" cx="250" cy="250" r="230" fill="url(#atmosphere)" /><circle cx="250" cy="250" r="194" fill="url(#ocean)" /><g clipPath="url(#earthClip)" fill="#799758" stroke="#9ab66d" strokeWidth="2"><path d="M55 173c31-19 52-15 73-32l39 8 21 32-24 25-37-8-28 25-34-14z" /><path d="M164 211l42 8 19 34-12 42-28 32-18 70-23-12-3-58-20-36 14-34z" /><path d="M251 112l35-22 54 13 26 35-34 20-35-7-18 28-34-24z" /><path d="M317 170l56-13 41 30-4 29-41 16-27 45-33-25 13-39-27-20z" /><path d="M364 282l45-18 58 28-8 55-45 18-22-29-32-8z" /><path d="M262 308l44-21 31 28-12 38 22 37-35 40-33-18-17-45z" /><path d="M118 320l35-12 21 28-19 39-35 5-19-29z" /></g><g clipPath="url(#earthClip)" fill="none" stroke="#eef2df" strokeLinecap="round" opacity=".28" filter="url(#cloudBlur)"><path d="M70 190c64-35 104 9 166-22s101 2 177-30" strokeWidth="15" /><path d="M136 285c56 20 93-28 153 1s104-5 156-28" strokeWidth="11" /><path d="M205 390c50-35 104 8 174-15" strokeWidth="13" /></g><circle cx="250" cy="250" r="194" fill="none" stroke="#b5e4d8" strokeOpacity=".5" strokeWidth="2" /></svg><span className="earth-glint" /></div> }

function EarthTexture({ className = '' }: { className?: string }) { return <div className={`earth-visual ${className}`} aria-label="Illustration of planet Earth"><svg viewBox="0 0 500 500" role="img" aria-hidden="true"><defs><radialGradient id="earthOcean" cx="31%" cy="27%" r="76%"><stop offset="0" stopColor="#4dabc0" /><stop offset=".42" stopColor="#176c82" /><stop offset=".78" stopColor="#0b4257" /><stop offset="1" stopColor="#041e31" /></radialGradient><radialGradient id="earthAtmosphere"><stop offset="71%" stopColor="#a9eced" stopOpacity="0" /><stop offset="88%" stopColor="#8bd9df" stopOpacity=".42" /><stop offset="100%" stopColor="#b9f0e7" stopOpacity="0" /></radialGradient><linearGradient id="earthNight" x1="0" y1="0" x2="1" y2=".65"><stop stopColor="#031a2b" stopOpacity=".68" /><stop offset=".5" stopColor="#031a2b" stopOpacity=".08" /><stop offset="1" stopColor="#031a2b" stopOpacity="0" /></linearGradient><filter id="earthCloudBlur"><feGaussianBlur stdDeviation="3.5" /></filter><clipPath id="earthClipTwo"><circle cx="250" cy="250" r="194" /></clipPath></defs><circle className="earth-atmosphere" cx="250" cy="250" r="230" fill="url(#earthAtmosphere)" /><circle cx="250" cy="250" r="194" fill="url(#earthOcean)" /><g clipPath="url(#earthClipTwo)" stroke="#b4c979" strokeWidth="1.3" strokeLinejoin="round"><path fill="#729653" d="M54 166c18-20 36-20 51-37l30 2 25-17 40 12 19 26-13 21-30 8-12 24-26 8-20 24-24-10-28 8-20-21z" /><path fill="#8d9860" d="M178 229l27 5 18 27-8 31-21 21-13 48-17 39-18-8 1-33-19-29 10-33-3-27z" /><path fill="#8b874f" d="M257 112l24-26 49 7 27 19 22 29-20 20-34-4-17 23-27-10-30-29z" /><path fill="#719554" d="M327 154l47-9 46 20 27 31-14 30-42 7-22 30-30-14 7-32-30-23z" /><path fill="#8e9656" d="M365 259l39-18 47 18 27 31-13 46-34 19-29-18-31 4-17-34z" /><path fill="#a1a05f" d="M278 304l38-17 25 22-6 34 19 29-24 40-30 16-28-23-7-43-18-31z" /><path fill="#728c57" d="M393 352l30 5 23 24-17 29-44 3-19-24z" /><path fill="#80965e" d="M112 302l29-12 21 19-13 37-28 13-25-23z" /></g><g clipPath="url(#earthClipTwo)" fill="none" stroke="#f5f7e9" strokeLinecap="round" opacity=".45" filter="url(#earthCloudBlur)"><path d="M48 194c51-35 84-3 130-22 39-16 69-5 103-20" strokeWidth="13" /><path d="M222 138c43 17 67 3 105 20 40 18 73 2 115-20" strokeWidth="9" /><path d="M129 281c44 18 80-14 122 1 40 15 66 3 119-23" strokeWidth="12" /><path d="M245 379c39-25 72 7 125-12" strokeWidth="10" /></g><circle cx="250" cy="250" r="194" fill="url(#earthNight)" /><path d="M91 141A194 194 0 0 1 366 93" fill="none" stroke="#d7f5eb" strokeOpacity=".58" strokeWidth="3" /><circle cx="250" cy="250" r="194" fill="none" stroke="#b8edf0" strokeOpacity=".7" strokeWidth="2" /></svg><span className="earth-glint" /></div> }

function EarthAsset({ className = '' }: { className?: string }) { return <div className={`earth-image ${className}`}><img src={earthAsset} alt="Planet Earth" draggable="false" /><span className="earth-image-atmosphere" /></div> }

function Hero({ onRegister }: { onRegister: () => void }) {
  const [pos, setPos] = useState({ x: 0, y: 0 })
  return <section className="hero" id="top" onMouseMove={(e) => { setPos({ x: (e.clientX / window.innerWidth - .5) * 10, y: (e.clientY / window.innerHeight - .5) * 8 }) }}>
    <div className="hero-grid" />
    <div className="orbital orbital-one" style={{ transform: `translate(${pos.x}px, ${pos.y}px)` }} /><div className="orbital orbital-two" style={{ transform: `translate(${-pos.x}px, ${-pos.y}px)` }} />
    <div className="hero-copy container"><div className="eyebrow"><span className="pulse" /> FC / OPEN CALL 2026</div><h1>Build<br /><em>for</em> Earth<span className="asterisk">✳</span></h1><p className="hero-sub">A FirstCommit hackathon for young builders creating technology for the real world.</p><div className="hero-actions"><button className="button" onClick={onRegister}>Register now <Arrow /></button><a className="text-link" href="#about">Explore the brief <span>↓</span></a></div><p className="hero-meta">AGES 13–21 <b>•</b> HOSTED BY FIRSTCOMMIT</p></div>
    <div className="hero-earth"><EarthAsset /></div><div className="hero-readout"><span>FIELD NOTE 001</span><b>BUILD / OBSERVE / SHARE</b><div className="readout-line"><i /></div><small>PLANET EARTH / 01<br />ATMOSPHERE: ACTIVE</small></div>
    <div className="terrain"><div className="sun" /><div className="ridge ridge-back" /><div className="ridge ridge-front" /><div className="grass-lines" /></div><div className="scroll-cue">SCROLL TO EXPLORE <span>↓</span></div>
  </section>
}

function About() { return <section className="about section container" id="about"><div className="about-aside"><SectionLabel>THE BRIEF / 01</SectionLabel><div className="mini-earth"><EarthAsset /><div className="earth-ring ring-a" /><div className="earth-ring ring-b" /><span>ONE PLANET<br /><b>∞ POSSIBILITIES</b></span></div></div><div className="about-copy"><h2>Build something<br /><span>that matters.</span></h2><p className="lead">The planet is a complex system. So are the communities that call it home. We are looking for young people with the curiosity to understand a problem, and the determination to build a way forward.</p><p>Build for Earth asks you to tackle a real-world challenge with technology. Not just a pitch deck. Not a thought experiment. A working prototype that someone could use, test, or take further.</p><div className="tag-list">{['Environment', 'Energy', 'Water', 'Waste', 'Earth observation', 'Robotics', 'Smart cities', 'Agriculture', 'Climate'].map(x => <span key={x}>{x}</span>)}</div></div></section> }

function Challenge() { return <section className="dark-section section" id="challenge"><div className="container"><div className="section-top"><div><SectionLabel>WHERE TO START / 02</SectionLabel><h2>Pick a problem.<br /><span>Make it tangible.</span></h2></div><p>These are starting points, not constraints. The most important category is the one you can turn into a working thing.</p></div><div className="challenge-grid">{challenges.map(c => <article className={`challenge-card ${c.tone}`} key={c.number}><div className="card-top"><span>{c.number}</span><strong>{c.icon}</strong></div><h3>{c.title}</h3><p>{c.text}</p><span className="card-arrow">↗</span></article>)}</div></div></section> }

function Ideas() { const [selected, setSelected] = useState(impactProjects[0]); const [map, setMap] = useState({ x: 0, y: 0, scale: 1 }); const [drag, setDrag] = useState<{ x: number; y: number } | null>(null); const move = (e: PointerEvent<HTMLDivElement>) => { if (!drag) return; setMap(m => ({ ...m, x: m.x + e.clientX - drag.x, y: m.y + e.clientY - drag.y })); setDrag({ x: e.clientX, y: e.clientY }) }; return <section className="ideas section container"><div className="ideas-title"><SectionLabel>THE POSSIBILITY FIELD / 03</SectionLabel><h2>What can<br /><span>you build?</span></h2><p>Imagine the first version. Then make it real.</p></div><div className="impact-explorer"><div className="map-toolbar"><span>IMPACT MAP / LIVE SAMPLE</span><div><button aria-label="Zoom out" onClick={() => setMap(m => ({ ...m, scale: Math.max(.8, m.scale - .15) }))}>−</button><button aria-label="Zoom in" onClick={() => setMap(m => ({ ...m, scale: Math.min(1.7, m.scale + .15) }))}>+</button><button aria-label="Reset map" onClick={() => setMap({ x: 0, y: 0, scale: 1 })}>RESET</button></div></div><div className="map-stage" onPointerDown={e => setDrag({ x: e.clientX, y: e.clientY })} onPointerMove={move} onPointerUp={() => setDrag(null)} onPointerCancel={() => setDrag(null)} onPointerLeave={() => setDrag(null)}><div className="map-globe" style={{ transform: `translate(${map.x}px,${map.y}px) scale(${map.scale})` }}><div className="map-sphere-layer"><EarthAsset className="map-earth" />{impactProjects.map(project => <button className={`map-marker ${selected.id === project.id ? 'selected' : ''}`} style={{ left: `${project.x}%`, top: `${project.y}%` }} key={project.id} onClick={() => setSelected(project)} aria-label={`Show impact project in ${project.location}`}><span>{project.id}</span></button>)}</div></div><span className="map-hint">DRAG TO EXPLORE / SELECT A SIGNAL</span></div><div className="impact-panel"><span className="panel-label">SELECTED SIGNAL / {selected.id}</span><h3>{selected.location}</h3><dl><div><dt>PROBLEM</dt><dd>{selected.problem}</dd></div><div><dt>TECHNOLOGY</dt><dd>{selected.technology}</dd></div><div><dt>IMPACT</dt><dd>{selected.impact}</dd></div></dl></div></div><div className="ideas-note"><span className="note-line" />Examples only — your project can be anything that addresses a meaningful real-world problem.</div></section> }

function How() { const steps = [['01', 'Discover', 'Find a real problem worth solving.'], ['02', 'Build', 'Turn your idea into a working prototype.'], ['03', 'Submit', 'Document your project and show what you built.'], ['04', 'Share', 'Demo your project and compete for prizes.']]; return <section className="how section"><div className="container"><SectionLabel>THE FLIGHT PLAN / 04</SectionLabel><h2>From signal<br /><span>to solution.</span></h2><div className="steps">{steps.map((s, i) => <div className="step" key={s[0]}><div className="step-number">{s[0]}</div><div className="step-connector" /><h3>{s[1]}</h3><p>{s[2]}</p><span className="step-dot" /></div>)}</div></div></section> }

function Timeline() { const events = [['01', 'Registration opens', '05 / 01 / 26'], ['02', 'Hacking begins', '05 / 22 / 26'], ['03', 'Midpoint check-in', '05 / 30 / 26'], ['04', 'Submission deadline', '06 / 07 / 26'], ['05', 'Judging', '06 / 12 / 26'], ['06', 'Winners announced', '06 / 14 / 26']]; return <section className="timeline-section section" id="timeline"><div className="container"><div className="timeline-heading"><SectionLabel>MARK YOUR CALENDAR / 05</SectionLabel><h2>The orbit<br /><span>starts here.</span></h2><p>Dates are placeholders while we lock in the next mission window.</p></div><div className="timeline">{events.map((e, i) => <div className={`event ${i === 0 ? 'active' : ''}`} key={e[0]}><span className="event-num">{e[0]}</span><div className="event-line" /><div><h3>{e[1]}</h3><time>{e[2]}</time></div></div>)}</div></div></section> }

const prizes = [['Best Overall', '$5,000', 'For the project that brings it all together.'], ['Best Environmental Impact', '$2,500', 'For a solution with measurable potential.'], ['Best Hardware Project', '$2,500', 'For an excellent physical build.'], ['Best Earth & Space Project', '$2,500', 'For seeing our planet from a new angle.'], ['Most Creative', '$1,000', 'For an unexpected, brilliant approach.'], ['Best Research', '$1,000', 'For a rigorous path from question to insight.']];
function Prizes() { return <section className="prizes section" id="prizes"><div className="container"><div className="section-top"><div><SectionLabel>RECOGNITION / 06</SectionLabel><h2>Build it.<br /><span>Take it further.</span></h2></div><p>Prize amounts are placeholders and will be updated as sponsorship is finalized.</p></div><div className="prize-grid">{prizes.map((p, i) => <article className={`prize-card p-${i}`} key={p[0]}><span className="prize-index">0{i + 1}</span><h3>{p[0]}</h3><strong>{p[1]}</strong><p>{p[2]}</p></article>)}</div><div className="beyond"><div><SectionLabel>SPECIAL RECOGNITION</SectionLabel><h3>Build Beyond <span>↗</span></h3></div><p>For a promising project with the potential to keep growing after the hackathon. This award supports the next step.</p><strong>TBD</strong></div></div></section> }

function Sponsors() { return <section className="sponsors section" id="sponsors"><div className="container sponsor-layout"><div><SectionLabel>THE CREW / 07</SectionLabel><h2>Built by many.<br /><span>Backed by you.</span></h2><p>We are bringing together people who believe young builders deserve a real place at the table.</p><a className="text-link dark-link" href="mailto:hello@firstcommit.xyz">Interested in supporting young builders? <b>Become a partner ↗</b></a></div><div className="partner-grid">{['PARTNER / 01', 'PARTNER / 02', 'PARTNER / 03', 'PARTNER / 04'].map(x => <div className="partner" key={x}><span>✳</span>{x}<small>YOUR LOGO HERE</small></div>)}</div></div></section> }

function FirstCommit() { return <section className="firstcommit"><div className="container fc-inner"><div className="fc-symbol">FC<span>↗</span></div><div><SectionLabel>THE ORGANIZER / 08</SectionLabel><h2>Powered by<br /><span>FirstCommit.</span></h2><p>FirstCommit is a youth-focused technology community creating opportunities for the next generation of builders. We help young people ages 13–21 learn, build, and share technology through hackathons and hands-on experiences.</p><a className="button button-light" href="https://firstcommit.xyz" target="_blank" rel="noreferrer">Visit FirstCommit <Arrow /></a></div></div></section> }

function FAQ() { const [active, setActive] = useState(0); return <section className="faq section" id="faq"><div className="container faq-layout"><div><SectionLabel>GOOD QUESTIONS / 09</SectionLabel><h2>Before<br /><span>liftoff.</span></h2><p>Still curious? Send a signal to <a href="mailto:hello@firstcommit.xyz">hello@firstcommit.xyz</a>.</p></div><div className="faq-list">{faqs.map(([q, a], i) => <div className={`faq-item ${i === active ? 'is-active' : ''}`} key={q}><button onClick={() => setActive(i)} aria-expanded={i === active}><span>{q}</span><b>+</b></button>{i === active && <p>{a}</p>}</div>)}</div></div></section> }

function FinalCTA({ onRegister }: { onRegister: () => void }) { return <section className="final-cta" id="register"><div className="final-grid" /><div className="final-orbit" /><div className="container"><SectionLabel>YOUR TURN / 10</SectionLabel><h2>The planet has<br /><em>problems.</em><br /><span>Build something.</span></h2><p>Join young builders around the world and turn an idea into something real.</p><button className="button button-light" onClick={onRegister}>Register for Build for Earth <Arrow /></button></div><div className="final-terrain"/></section> }

function Footer({ onRegister }: { onRegister: () => void }) { return <footer><div className="container footer-main"><Logo /><span className="footer-tag">A FIRSTCOMMIT HACKATHON.<br />MADE FOR THE REAL WORLD.</span><div className="footer-links"><a href="https://firstcommit.xyz">FirstCommit</a><a href="#register" onClick={event => { event.preventDefault(); onRegister() }}>Register</a><a href="#faq">FAQ</a><a href="mailto:hello@firstcommit.xyz">Contact</a><a href="#">Privacy</a><a href="https://hcb.hackclub.com/donations/start/firstcommit">Donate</a></div></div><div className="container footer-bottom"><span>© 2026 FIRSTCOMMIT</span><span>BUILT WITH CURIOSITY / <b>●</b> FOR EARTH</span></div></footer> }

function RegistrationModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null)
  const [form, setForm] = useState({ name: '', email: '' })
  const [errors, setErrors] = useState<{ name?: string; email?: string }>({})
  const [status, setStatus] = useState<'idle' | 'submitting' | 'success' | 'duplicate' | 'error'>('idle')
  const statusRef = useRef(status)
  statusRef.current = status

  useEffect(() => {
    if (!open) return
    setForm({ name: '', email: '' }); setErrors({}); setStatus('idle'); closeRef.current?.focus()
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape' && statusRef.current !== 'submitting') onClose() }
    window.addEventListener('keydown', onKeyDown)
    return () => { document.body.style.overflow = previousOverflow; window.removeEventListener('keydown', onKeyDown) }
  }, [open, onClose])

  if (!open) return null
  const validate = () => { const next: { name?: string; email?: string } = {}; if (form.name.trim().length < 2) next.name = 'Please enter your name.'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())) next.email = 'Please enter a valid email.'; setErrors(next); return Object.keys(next).length === 0 }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (status === 'submitting' || !validate()) return; setStatus('submitting'); try { const response = await fetch('/api/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.name.trim(), email: form.email.trim() }) }); const payload = await response.json().catch(() => null) as { code?: string } | null; if (response.status === 409 && payload?.code === 'duplicate') { setStatus('duplicate'); return } if (!response.ok) throw new Error('Registration failed'); setStatus('success') } catch { setStatus('error') } }
  return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget && status !== 'submitting') onClose() }}><div className="registration-modal" role="dialog" aria-modal="true" aria-labelledby="registration-title"><div className="modal-top"><span className="section-label"><span />REGISTRATION / 001</span><button className="modal-close" ref={closeRef} onClick={onClose} disabled={status === 'submitting'} aria-label="Close registration form">×</button></div>{status === 'success' ? <div className="modal-state"><span className="success-mark">✓</span><h2 id="registration-title">You’re on<br /><span>the list.</span></h2><p>We’ve received your registration. We will share the next mission briefing when registration opens.</p><button className="button" onClick={onClose}>Back to the mission <Arrow /></button></div> : <><div className="modal-heading"><h2 id="registration-title">Ready to<br /><span>build?</span></h2><p>Leave your details and we will keep your place in the signal log.</p></div><form onSubmit={submit} noValidate><label>Name<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} autoComplete="name" autoFocus aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? 'name-error' : undefined} placeholder="Your full name" />{errors.name && <small id="name-error" className="field-error">{errors.name}</small>}</label><label>Email<input value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} type="email" inputMode="email" autoComplete="email" aria-invalid={Boolean(errors.email)} aria-describedby={errors.email ? 'email-error' : undefined} placeholder="you@example.com" />{errors.email && <small id="email-error" className="field-error">{errors.email}</small>}</label>{status === 'duplicate' && <p className="form-message" role="status">You’re already registered! Try a different email if needed.</p>}{status === 'error' && <p className="form-error" role="alert">We couldn’t complete your registration. Please try again.</p>}<button className="button modal-submit" type="submit" disabled={status === 'submitting'}>{status === 'submitting' ? <><span className="spinner" />Registering...</> : <>Register for Build for Earth <Arrow /></>}</button><p className="modal-legal">By registering, you agree to receive event updates from FirstCommit.</p></form></>}</div></div>
}

function App() { const [registrationOpen, setRegistrationOpen] = useState(false); const openRegistration = () => setRegistrationOpen(true); useEffect(() => { document.documentElement.style.scrollBehavior = 'smooth'; return () => { document.documentElement.style.scrollBehavior = 'auto' } }, []); return <><Nav onRegister={openRegistration} /><main><Hero onRegister={openRegistration} /><About /><Challenge /><Ideas /><How /><Timeline /><Prizes /><Sponsors /><FirstCommit /><FAQ /><FinalCTA onRegister={openRegistration} /></main><Footer onRegister={openRegistration} /><RegistrationModal open={registrationOpen} onClose={() => setRegistrationOpen(false)} /></> }

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
